### ISSUE TITLE
Old SmartOS articles

### ISSUE THREAD

**Issue by neuroserve** [brianewell/ansible-smartos-tricks#1]
Hi Brian,

I didn't know how to get in contact with you, thus I try this. Following up on a thread on smartos-discuss (https://smartos.topicbox.com/groups/smartos-discuss/Tb6e04c99ef7168ef/opendkim-postfix) and your post on https://blog.brianewell.com/hello-world/ I wanted to find out, whether it would be possible to publish your older articles on SmartOS - even though your focus is on automation now. I guess (and the requests on smartos-discuss seem to show that), that there's still demand for "unautomated" setups on SmartOS (and could be used for a basis for automated setups, too). If you don't want to leave your articles in an archive section of your new blog, it might be possible to create a "how-to" section in the smartos-wiki and add them there.

I'd be pleased to hear from you in this case :-)

**Comment by brianewell** [comment]
Just posted a response on topicbox.

In short, I'll try to get that content restored later today.

**Comment by neuroserve** [comment]
Great. That sounds promising.
